package manageSystem.dataBase;

public class DataBaseAccess {
    public static class getPrograms{

        public getPrograms(){

        }
        public static String getMainProgramJSONstring(){
            //return  "\"{\"blocks\":{\"languageVersion\":0,\"blocks\":[{\"type\":\"initialPosition\",\"id\":\"X-6.BN2w0B(+#]Q:$UC1\",\"x\":164,\"y\":131,\"fields\":{\"POSITION_NAME\":\"positionA\"},\"next\":{\"block\":{\"type\":\"moveTo\",\"id\":\"jL-lUsLjyLX/t(n;Q.Qx\",\"fields\":{\"POSITION_NAME\":\"positionB\"},\"next\":{\"block\":{\"type\":\"moveTo\",\"id\":\"(_;sXN7]sN29VdZ_dRsh\",\"fields\":{\"POSITION_NAME\":\"positionC\"},\"next\":{\"block\":{\"type\":\"controls_ifelse\",\"id\":\"^vZ[5aNVFBuM#GuS1scY\",\"inputs\":{\"IF0\":{\"block\":{\"type\":\"logic_compare\",\"id\":\"(.I#v.28`(XP_9(3W:kx\",\"fields\":{\"OP\":\"EQ\"},\"inputs\":{\"A\":{\"block\":{\"type\":\"getCurrentPosition\",\"id\":\"QRAZEL*O$Y`Ndp1}wp7x\",\"fields\":{\"AXIS\":\"X\"}}},\"B\":{\"block\":{\"type\":\"math_number\",\"id\":\"vRTy,s/#LhX;_qP6,D7)\",\"fields\":{\"NUM\":0}}}}}},\"DO0\":{\"block\":{\"type\":\"moveTo\",\"id\":\"*ytlf_?N^Au{D*j4.O{o\",\"fields\":{\"POSITION_NAME\":\"positionD\"}}},\"ELSE\":{\"block\":{\"type\":\"wait_seconds\",\"id\":\"Q4$oBH9m.st)[)Xaj]Px\",\"fields\":{\"SECONDS\":1}}}},\"next\":{\"block\":{\"type\":\"debug_activate_notification\",\"id\":\"z]K?d%(;a!P):N*g3o]a\",\"fields\":{\"TEXT\":\"Текст уведомления\"}}}}}}}}}}]}}\"\n";
            return "'{\"blocks\":{\"languageVersion\":0,\"blocks\":[{\"type\":\"initialPosition\",\"id\":\"}fSyEWv/,g~d-H}L-SZ2\",\"x\":171,\"y\":81,\"fields\":{\"POSITION_NAME\":\"\"},\"next\":{\"block\":{\"type\":\"controls_ifelse\",\"id\":\"|hp;V{tMB%o,]:ehS=:r\",\"inputs\":{\"IF0\":{\"block\":{\"type\":\"logic_compare\",\"id\":\"_4^*Xpz,Gbmv%VwZS!{.\",\"fields\":{\"OP\":\"EQ\"},\"inputs\":{\"A\":{\"block\":{\"type\":\"math_number\",\"id\":\"j%NBwup@RM6l![B5.oFP\",\"fields\":{\"NUM\":0}}},\"B\":{\"block\":{\"type\":\"math_number\",\"id\":\"k.d*og:S;XRO=O%tL5-L\",\"fields\":{\"NUM\":0}}}}}},\"DO0\":{\"block\":{\"type\":\"controls_ifelse\",\"id\":\"Hws+zpHUUhxL$dtW2q9J\",\"inputs\":{\"IF0\":{\"block\":{\"type\":\"logic_compare\",\"id\":\"Pd5^q8OSl8}Wgz9*w5Fp\",\"fields\":{\"OP\":\"EQ\"},\"inputs\":{\"A\":{\"block\":{\"type\":\"math_number\",\"id\":\"7o:^XE6[_mSGm%9S``xY\",\"fields\":{\"NUM\":1}}},\"B\":{\"block\":{\"type\":\"math_number\",\"id\":\"KL^LS8vbi!2e!(2_[M+R\",\"fields\":{\"NUM\":1}}}}}},\"DO0\":{\"block\":{\"type\":\"debug_activate_notification\",\"id\":\"J%14ZKVM@ZbPQ~(6.nGy\",\"fields\":{\"TEXT\":\"Условие 1\"}}},\"ELSE\":{\"block\":{\"type\":\"debug_activate_notification\",\"id\":\"ueg^C+pUj%AV/ZBd~0Yz\",\"fields\":{\"TEXT\":\"Условие 2\"}}}}}},\"ELSE\":{\"block\":{\"type\":\"controls_ifelse\",\"id\":\"rh;:iZ6~qBFIGk=PjKPX\",\"inputs\":{\"IF0\":{\"block\":{\"type\":\"logic_compare\",\"id\":\"h2scu~l80Q`x`K)*hMp2\",\"fields\":{\"OP\":\"EQ\"},\"inputs\":{\"A\":{\"block\":{\"type\":\"math_number\",\"id\":\"Q*U%g[/vjY!AUWg+EMDK\",\"fields\":{\"NUM\":2}}},\"B\":{\"block\":{\"type\":\"math_number\",\"id\":\"FzU(qjzN7R*Xl.Bq6mOx\",\"fields\":{\"NUM\":2}}}}}},\"DO0\":{\"block\":{\"type\":\"debug_activate_notification\",\"id\":\"BA[~?N:1bZ*/1?N0-W~:\",\"fields\":{\"TEXT\":\"Условие 3\"}}},\"ELSE\":{\"block\":{\"type\":\"debug_activate_notification\",\"id\":\"FOD[`STRk4jv6*(?jGgQ\",\"fields\":{\"TEXT\":\"Условие 4\"}}}}}}}}}}]}}'\n";

        }
    }
}
